Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Strive4Tri.Models;

namespace Strive4Tri.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "What Strive4Tri is all about";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Feel free to contact me. Here is how you can get to me";

            return View();
        }

        public IActionResult Help()
        {
            ViewData["Message"] = "All the questions of the history of mankind answered, for true";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PredictorController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Strive4Tri.ViewModels;
using Strive4Tri.Strava;
using System.Linq;
using System.Collections.Generic;
using Strive4Tri.Strive;
using System;

namespace Strive4Tri.Controllers
{
    public class PredictorController : Controller
    {
        private string RedirectUrl
        {
            get
            {
                return $"{Request.Scheme}://{Request.Host}/Predictor/Callback";
            }
        }

        // GET: Predictors
        public async Task<ActionResult> Index()
        {
            var authenticator = StravaAuthenticator.CreateAuthenticator(RedirectUrl, HttpContext);

            if (!authenticator.IsAuthenticated)
            {
                var loginUri = await authenticator.GetLoginLinkUri();
                return Redirect(loginUri.AbsoluteUri);
            }

            var predictor = new Predictor(authenticator);
            return ProcessActionResult(predictor);
        }

        public ActionResult Sample()
        {
            var predictor = new Predictor();
            return ProcessActionResult(predictor);
        }

        private ActionResult ProcessActionResult(Predictor predictor)
        {
            var viewModel = new PredictorViewModel();
            var runningPerformance = predictor.GetRunningPerformance();
            var cyclingPerformance = predictor.GetCyclingPerformance();
            var swimmingPerformance = predictor.GetSwimmingPerformance();
            
            if (runningPerformance.Sum(s => s.Value) == 0)
            {
                viewModel.RunningPerformance = null;
            }
            else
            {
                for (var i = 0; i < runningPerformance.Count; i++)
                {
                    if (runningPerformance[i].Value > 0)
                    {
                        viewModel.RunningPerformance.Add(new ActivityBase
                        {
                            Distance = runningPerformance[i].Key,
                            Performance = runningPerformance[i].Value,
                            Time = TimeSpan.FromMinutes(runningPerformance[i].Key * runningPerformance[i].Value)
                        });
                    }

                    if (i < runningPerformance.Count - 1 && runningPerformance[i + 1].Value == 0)
                    {
                        // If there's no information for a given distance, we just use the previous distance (but 5% slower, just an arbitrary value, no science here)
                        viewModel.RunningPerformance.Add(new ActivityBase
                        {
                            Distance = runningPerformance[i + 1].Key,
                            Performance = viewModel.RunningPerformance[i].Performance * 1.05,
                            Time = TimeSpan.FromMinutes(runningPerformance[i + 1].Key * viewModel.RunningPerformance[i].Performance * 1.05)
                        });
                    }
                }

                viewModel.RunningPerformance.RemoveAt(0);
            }

            if (cyclingPerformance.Sum(s => s.Value) == 0)
            {
                viewModel.CyclingPerformance = null;
            }
            else
            {
                for (var i = 0; i < cyclingPerformance.Count; i++)
                {
                    if (cyclingPerformance[i].Value > 0)
                    {
                        viewModel.CyclingPerformance.Add(new ActivityBase
                        {
                            Distance = cyclingPerformance[i].Key,
                            Performance = cyclingPerformance[i].Value,
                            Time = TimeSpan.FromHours(cyclingPerformance[i].Key / cyclingPerformance[i].Value)
                        });
                    }

                    if (i < cyclingPerformance.Count - 1 && cyclingPerformance[i + 1].Value == 0)
                    {
                        // If there's no information for a given distance, we just use the previous distance (but 5% slower, just an arbitrary value, no science here)
                        viewModel.CyclingPerformance.Add(new ActivityBase
                        {
                            Distance = cyclingPerformance[i + 1].Key,
                            Performance = viewModel.CyclingPerformance[i].Performance * 0.95,
                            Time = TimeSpan.FromHours(cyclingPerformance[i + 1].Key / viewModel.CyclingPerformance[i].Performance * 0.95)
                        });
                    }
                }

                viewModel.CyclingPerformance.RemoveAt(0);
            }

            if (swimmingPerformance.Sum(s => s.Value) == 0)
            {
                viewModel.SwimmingPerformance = null;
            }
            else
            {
                for (var i = 0; i < swimmingPerformance.Count; i++)
                {
                    if (swimmingPerformance[i].Value > 0)
                    {
                        viewModel.SwimmingPerformance.Add(new ActivityBase
                        {
                            Distance = swimmingPerformance[i].Key,
                            Performance = swimmingPerformance[i].Value,
                            Time = TimeSpan.FromMinutes(swimmingPerformance[i].Key / 100 * swimmingPerformance[i].Value)
                        });
                    }

                    if (i < swimmingPerformance.Count - 1 && swimmingPerformance[i + 1].Value == 0)
                    {
                        // If there's no information for a given distance, we just use the previous distance (but 5% slower, just an arbitrary value, no science here)
                        viewModel.SwimmingPerformance.Add(new ActivityBase
                        {
                            Distance = swimmingPerformance[i + 1].Key,
                            Performance = viewModel.SwimmingPerformance[i].Performance * 1.05,
                            Time = TimeSpan.FromMinutes(swimmingPerformance[i + 1].Key / 100 * viewModel.SwimmingPerformance[i].Performance * 1.05)
                        });
                    }
                }

                viewModel.SwimmingPerformance.RemoveAt(0);
            }

            return View("Index", viewModel);
        }

        public async Task<ActionResult> Callback()
        {
            var authenticator = StravaAuthenticator.CreateAuthenticator(RedirectUrl, HttpContext);
            await authenticator.OnPageLoaded(RedirectUrl, Request.QueryString.ToUriComponent());
            return RedirectToAction("Index");
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="row">
    <div class="col-md-4">
        <h2>Context</h2>
        <p><strong>Strava</strong> is the #1 app for runners and cyclists, but it also supports swimming. With it you can record your activities using their mobile app or any other compatible app or device.</p>
    </div>
    <div class="col-md-4">
        <h2>Problem</h2>
        <p><strong>Strava</strong> offers athletes the possibility to keep track of all their activities, like running, swimming and cycling, whether they are regular workouts, commutes or races, and does provide an insight of performance during time. But what Strava does not provide is the ability to predict how this performance will influence the results of a race.</p>
    </div>
    <div class="col-md-4">
        <h2>Solution</h2>
        <p>Strive: To make great efforts to achieve or obtain</p>
        <p><strong>Strive4Tri</strong> (strive for triathlon) comes to the rescue by predicting how your training records should boot your performance in a race.</p>
        <p>
            No matters whether you are a <strong>runner</strong> and are aiming to rock the Boston Marathon or just preparing for your first 5K charity race, or a <strong>cyclist</strong> training to survive your first Grand Fondo or conquer the Alpe D’Huez. Or maybe a <strong>swimmer</strong> or a <strong>triathlete</strong>? Strive4Tri is aimed just for you.
        </p>
    </div>
</div>
<div class="starter-template text-center">
    <h1>Leaving all the "marketing" behind...</h1>
    <p class="lead">The true story is, this app was built as a code test for Symbio.</p>
</div>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<div class="row mb-2">
    <div class="col-md-6">
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <strong class="d-inline-block mb-2 text-primary">Details</strong>
                <p class="card-text mb-auto">
                    <strong>Name:</strong> Vladimir Urbano<br />
                    <strong>Phone number:</strong> +56 9 8595 0200<br />
                    <strong>Email:</strong> <a href="mailto:vladimirnul@gmail.com">vladimirnul@gmail.com</a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <strong class="d-inline-block mb-2 text-success">Address</strong>
                <p class="card-text mb-auto">
                    Nueva Príncipe de Gales 50, 508<br />
                    7860374 La Reina<br />
                    Chile
                </p>
            </div>
        </div>
    </div>
</div>

Views/Home/Help.cshtml
@{
    ViewData["Title"] = "Help";
}

<div class="starter-template text-center">
    <p class="lead">"Just when we think we have all the answers, they change all the questions"</p>
</div>
<div class="blog-post">
    <h2 class="blog-post-title">How it works</h2>
    <p>You need to authorize the app to work with Strava, you just need to do this once. <strong>Or</strong> you can use the test data to play around.</p>
    <p>Once authorized, you just need to wait and the results will show up, you don't need to choose anything, <strong>Strive4Tri</strong> will see which sports you have been practicing the last days and show the best results.</p>
    <p>Enjoy!</p>
</div>

Views/Home/Index.cshtml
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light strive-banner">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
        <h1 class="display-4 font-weight-normal">Ready to strive</h1>
        <p class="lead font-weight-normal">Check the "about" and "help" sections to begin with, or jump direct to "strive" behind to see your predictions.</p>
        <a class="btn btn-secondary" role="button" asp-area="" asp-controller="Predictor" asp-action="Sample">Use sample data</a>
        <a class="btn btn-secondary" role="button" asp-area="" asp-controller="Predictor" asp-action="Index">Strive!</a>
    </div>
</div>